### ISSUE TITLE
Container exited with code 139

### ISSUE THREAD

**Issue by gitviola** [kynetiv/docker-selenium-pi#1]
When I try to run the container on my raspberry pi it always shows me this error:

`exited with code 139`

It doesn't show any other output 🤔
Seems to be an error that ideates that it's out of memory. Have you managed to run it on your raspberry pi?

**Comment by kynetiv** [comment]
I have been running the standalone chrome on my pi 2. Works fairly well for me, although selenium does seem to be a memory hog in general. I'm curious what your docker run command looks like?

**Comment by gitviola** [comment]
@kynetiv This is my `docker-compose.yml` file:

```
version: "2"
services:
  selenium-chrome:
    image: kynetiv/selenium-standalone-chromium-pi
    ports:
      - "4444:4444"
    volumes:
      - ./.cache:/home/seluser/Downloads # for figo
      - ./export:/usr/app/export
```

So it's a basic `docker-compose up selenium-chrome`:

```bash
pi@raspberrypi:~/ynab-bank-importer $ docker-compose up selenium-chrome
Recreating ynabbankimporter_selenium-chrome_1 ... 
Recreating ynabbankimporter_selenium-chrome_1 ... done
Attaching to ynabbankimporter_selenium-chrome_1
ynabbankimporter_selenium-chrome_1 exited with code 139
```
